swagger: "2.0"
info:
  title: "Go package seeker"
  version: "1.0.0"
  description: "指定したGoのパッケージから文字列を検索し、標準出力に出し、サーバモードも提供できるコマンドツール"
  contact:
    email: "y.tomoka64@gmail.com"
schemes:
- https
host: localhost:8000
basePath: "/"
produces:
  - application/json
paths:
  /search:
    get:
      operationId: Search
      responses:
        200:
          description: "Status OK. "

  /search/{directory}/{keyword}:
    parameters:
      - name: directory
        in: path
        type: string
        description: "get the directory of go package "
        required: true
      - name: keyword
        in: path
        type: string
        description: "get the keyword to search"
        required: true
    get:
      operationId: SearchProcess
      responses:
        200:
          description: StatusOK
        404:
          description: NotFound
